openapi: 3.0.0
info:
  title: GitHub API Documentation
  version: 1.0.0
servers:
  - url: https://api.github.com
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: []
paths:
  /user:
    get:
      summary: Get authenticated user information
      security:
        - BearerAuth: []
      responses:
        '200':
          description: A successful response
        '401':
          description: Unauthorized access
